name: Docker

on:
  release:
    types: [published]
jobs:
  check-secrets:
    uses: ./.github/workflows/check-secrets.yml
    with:
      secret_name: 'DOCKERHUB_USER'
  docker-release:
    needs: check-secrets
    if: needs.check-secrets.outputs.has-secrets == 'true'
    name: docker-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["dev", "lean", "lean310", "websocket", "dockerize"]
        platform: ["linux/amd64", "linux/arm64"]
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          GITHUB_RELEASE_TAG_NAME="${{ github.event.release.tag_name }}"
          ./scripts/docker_build_push.sh "$GITHUB_RELEASE_TAG_NAME" ${{ matrix.target }} ${{ matrix.platform }}
